REPORT ZESTUDOS1.

DATA: LV_TOTSA TYPE P DECIMALS 2,
      LV_HOUR  TYPE P DECIMALS 2.

PARAMETERS:
  LV_NAME  TYPE C LENGTH 15,
  LV_SAL   TYPE P DECIMALS 2,
  LV_EXTRA TYPE I,
  LV_OTHER TYPE I.

LV_HOUR = '7.27'.
LV_EXTRA = LV_HOUR * LV_EXTRA.
LV_TOTSA = ( LV_SAL + LV_EXTRA ) - LV_OTHER.


WRITE: 'Name: ', LV_NAME.
NEW-LINE.
WRITE: 'Salary: ', LV_SAL.
NEW-LINE.
WRITE: 'Extra Hour', LV_EXTRA.
NEW-LINE.
WRITE: 'Total Salary', LV_TOTSA.

